### ISSUE TITLE
"Versions" configuration page not working with SVN

### ISSUE THREAD

**Issue by shagr4th** [jutzig/jabylon#237]
I'm having a hard time to make this project work with SVN : in the "versions" subsection, I cannot add a lang. Either I got a blank configuration when I go back (meaning my changes were not saved), or I'm having this stack trace:

java.lang.ClassCastException: org.jabylon.properties.impl.ProjectLocaleImpl cannot be cast to org.jabylon.properties.ResourceFolder
        at org.jabylon.properties.util.PropertyResourceUtil.getOrCreateFolder(PropertyResourceUtil.java:285) ~[org.jabylon.properties_1.1.4.jar:na]
        at org.jabylon.properties.util.PropertyResourceUtil.createMissingChildren(PropertyResourceUtil.java:255) ~[org.jabylon.properties_1.1.4.jar:na]
        at org.jabylon.properties.util.PropertyResourceUtil.addNewLocale(PropertyResourceUtil.java:245) ~[org.jabylon.properties_1.1.4.jar:na]
        at org.jabylon.rest.ui.wicket.config.sections.VersionConfigSection$VersionConfig.applyLocaleList(VersionConfigSection.java:245) ~[org.jabylon.rest.ui_1.1.4.jar:na]
        at org.jabylon.rest.ui.wicket.config.sections.VersionConfigSection$VersionConfig.commit(VersionConfigSection.java:214) ~[org.jabylon.rest.ui_1.1.4.jar:na]
        at org.jabylon.rest.ui.wicket.config.SettingsPanel$1.commit(SettingsPanel.java:140) ~[org.jabylon.rest.ui_1.1.4.jar:na]
        at org.jabylon.rest.ui.wicket.config.SettingsPanel$1.onSubmit(SettingsPanel.java:130) ~[org.jabylon.rest.ui_1.1.4.jar:na]
        at org.apache.wicket.markup.html.form.Form$9.component(Form.java:1249) ~[org.apache.wicket.wicket-core_6.0.0.jar:6.0.0]
        at org.apache.wicket.markup.html.form.Form$9.component(Form.java:1243) ~[org.apache.wicket.wicket-core_6.0.0.jar:6.0.0]

**Comment by shagr4th** [comment]
Nevermind, the "rescan" button behavior is quite confusing but I understood it

**Comment by jutzig** [comment]
Do you remember what you did to end up with that Exception?

**Comment by shagr4th** [comment]
Now i can't reproduce it, but it was something like:

* add a project with only a single messages.properties file
* add "trunk" version without langs
* update and rescan
* add a translation lang and submit
* rescan (which were deleting the language I just added)
* add a translation lang and submit -> crash

**Comment by shagr4th** [comment]
I can reproduce it and now the scanner is not working at all again. I guess there is another factor at work here, i'll try to debug it

**Comment by jutzig** [comment]
Alternatively you could provide me with a sample project that reproduces the issue then I can fix it. Since it happens on rescan it is probably not directly related to SVN and the property files should be sifficient to reproduce

**Comment by shagr4th** [comment]
Sorry, I changed job some time ago, and haven't kept the usecase. No need to let this issue open I guess !
