### ISSUE TITLE
IndexOutOfBounds on scan

### ISSUE THREAD

**Issue by jutzig** [jutzig/jabylon#238]
Certain (long) paths cause an @IndexOutOfBoundsException@ when scanning.
See stacktrace below

```java
org.quartz.JobExecutionException: java.lang.ArrayIndexOutOfBoundsException: 22
	at org.jabylon.scheduler.internal.JabylonJob.execute(JabylonJob.java:98) ~[org.jabylon.scheduler-1.2.0-SNAPSHOT.jar:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) ~[quartz.jar:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [quartz.jar:na]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 22
	at org.eclipse.emf.common.util.URI$URIPool$FileAccessUnit.reset(URI.java:1583) ~[na:na]
	at org.eclipse.emf.common.util.Pool.doIntern(Pool.java:963) ~[na:na]
	at org.eclipse.emf.common.util.URI$URIPool.internFile(URI.java:1939) ~[na:na]
	at org.eclipse.emf.common.util.URI.createFileURI(URI.java:2579) ~[na:na]
	at org.jabylon.properties.util.PropertyResourceUtil.computeLocaleResourceLocation(PropertyResourceUtil.java:314) ~[na:na]
	at org.jabylon.properties.util.PropertyResourceUtil.createMissingChildren(PropertyResourceUtil.java:252) ~[na:na]
	at org.jabylon.properties.util.PropertyResourceUtil.createMissingDescriptorEntries(PropertyResourceUtil.java:127) ~[na:na]
	at org.jabylon.properties.impl.ProjectVersionImpl.fullScan(ProjectVersionImpl.java:178) ~[na:na]
	at org.jabylon.rest.ui.wicket.config.sections.ProjectVersionsConfigSection$10.run(ProjectVersionsConfigSection.java:353) ~[na:na]
	at org.jabylon.scheduler.internal.RunnableWithProgressWrapper.run(RunnableWithProgressWrapper.java:36) ~[org.jabylon.scheduler-1.2.0-SNAPSHOT.jar:na]
	at org.jabylon.scheduler.internal.JabylonJob.execute(JabylonJob.java:79) ~[org.jabylon.scheduler-1.2.0-SNAPSHOT.jar:na]
```

**Comment by jutzig** [comment]
This happened for paths like this `file:/C:/workspaces/jabylon/work/workspace/ets/develop/debug/rt.debug.debugger/src/main/java/com/seeburger/bicng/rt/debug/debugger/messages/messages_de_DE.properties`
