### ISSUE TITLE
Exception when trying to add branch whose name contains slashes

### ISSUE THREAD

**Issue by f-cramer** [jutzig/jabylon#267]
When trying to add a version from a branch whose name contains a slash (i.e. "feature/TERM-89-internationalisierung-des-terminals") the following exception is thrown:

```
org.apache.wicket.WicketRuntimeException: Method onFormSubmitted of interface org.apache.wicket.markup.html.form.IFormSubmitListener targeted at [Form [Component id = form]] on component [Form [Component id = form]] threw an exception
	at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:268) [76:org.apache.wicket.core:6.0.0]
	at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:216) [76:org.apache.wicket.core:6.0.0]
	at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.invokeListener(ListenerInterfaceRequestHandler.java:240) [76:org.apache.wicket.core:6.0.0]
	at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.respond(ListenerInterfaceRequestHandler.java:226) [76:org.apache.wicket.core:6.0.0]
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:814) [76:org.apache.wicket.core:6.0.0]
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64) [79:org.apache.wicket.request:6.0.0]
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:253) [76:org.apache.wicket.core:6.0.0]
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:210) [76:org.apache.wicket.core:6.0.0]
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:281) [76:org.apache.wicket.core:6.0.0]
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:188) [76:org.apache.wicket.core:6.0.0]
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:245) [76:org.apache.wicket.core:6.0.0]
	at org.jabylon.rest.ui.JabylonFilter.doFilter(JabylonFilter.java:89) [144:org.jabylon.rest.ui:1.3.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1751) [114:org.eclipse.jetty.servlet:9.3.15.v20161220]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) [114:org.eclipse.jetty.servlet:9.3.15.v20161220]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70) [162:org.ops4j.pax.web.pax-web-jetty:6.0.2]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [113:org.eclipse.jetty.server:9.3.15.v20161220]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [111:org.eclipse.jetty.security:9.3.15.v20161220]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [113:org.eclipse.jetty.server:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [113:org.eclipse.jetty.server:9.3.15.v20161220]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:284) [162:org.ops4j.pax.web.pax-web-jetty:6.0.2]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [114:org.eclipse.jetty.servlet:9.3.15.v20161220]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [113:org.eclipse.jetty.server:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [113:org.eclipse.jetty.server:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [113:org.eclipse.jetty.server:9.3.15.v20161220]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80) [162:org.ops4j.pax.web.pax-web-jetty:6.0.2]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [113:org.eclipse.jetty.server:9.3.15.v20161220]
	at org.eclipse.jetty.server.Server.handle(Server.java:534) [113:org.eclipse.jetty.server:9.3.15.v20161220]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [113:org.eclipse.jetty.server:9.3.15.v20161220]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [113:org.eclipse.jetty.server:9.3.15.v20161220]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [105:org.eclipse.jetty.io:9.3.15.v20161220]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [105:org.eclipse.jetty.io:9.3.15.v20161220]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [105:org.eclipse.jetty.io:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [116:org.eclipse.jetty.util:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [116:org.eclipse.jetty.util:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [116:org.eclipse.jetty.util:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [116:org.eclipse.jetty.util:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [116:org.eclipse.jetty.util:9.3.15.v20161220]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:258) ~[76:org.apache.wicket.core:6.0.0]
	... 37 more
Caused by: java.lang.IllegalArgumentException: invalid segment: feature/TERM-89-internationalisierung-des-terminals
	at org.eclipse.emf.common.util.URI.validateURI(URI.java:2747) ~[92:org.eclipse.emf.common:2.9.1.v20130827-0309]
	at org.eclipse.emf.common.util.URI$URIPool$URIComponentsAccessUnit.getInternalizedValue(URI.java:1802) ~[92:org.eclipse.emf.common:2.9.1.v20130827-0309]
	at org.eclipse.emf.common.util.URI$URIPool$URIComponentsAccessUnit.getInternalizedValue(URI.java:1) ~[92:org.eclipse.emf.common:2.9.1.v20130827-0309]
	at org.eclipse.emf.common.util.Pool.doIntern(Pool.java:959) ~[92:org.eclipse.emf.common:2.9.1.v20130827-0309]
	at org.eclipse.emf.common.util.URI$URIPool.intern(URI.java:1958) ~[92:org.eclipse.emf.common:2.9.1.v20130827-0309]
	at org.eclipse.emf.common.util.URI.createHierarchicalURI(URI.java:2398) ~[92:org.eclipse.emf.common:2.9.1.v20130827-0309]
	at org.jabylon.properties.impl.ResolvableImpl.toURI(ResolvableImpl.java:296) ~[?:?]
	at org.jabylon.common.resolver.impl.WorkspaceURIHandler.toURI(WorkspaceURIHandler.java:105) ~[137:org.jabylon.common:1.3.0]
	at org.jabylon.common.resolver.impl.URIResolverImpl.internalGetURI(URIResolverImpl.java:84) ~[137:org.jabylon.common:1.3.0]
	at org.jabylon.common.resolver.impl.URIResolverImpl.getURI(URIResolverImpl.java:92) ~[137:org.jabylon.common:1.3.0]
	at org.jabylon.common.util.PreferencesUtil.scopeFor(PreferencesUtil.java:66) ~[137:org.jabylon.common:1.3.0]
	at org.jabylon.rest.ui.wicket.config.SettingsPanel$1.onSubmit(SettingsPanel.java:134) ~[144:org.jabylon.rest.ui:1.3.0]
	at org.apache.wicket.markup.html.form.Form$9.component(Form.java:1249) ~[76:org.apache.wicket.core:6.0.0]
	at org.apache.wicket.markup.html.form.Form$9.component(Form.java:1243) ~[76:org.apache.wicket.core:6.0.0]
	at org.apache.wicket.util.visit.Visits.visitPostOrderHelper(Visits.java:274) ~[80:org.apache.wicket.util:6.0.0]
	at org.apache.wicket.util.visit.Visits.visitPostOrder(Visits.java:245) ~[80:org.apache.wicket.util:6.0.0]
	at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1242) ~[76:org.apache.wicket.core:6.0.0]
	at org.apache.wicket.markup.html.form.Form.process(Form.java:924) ~[76:org.apache.wicket.core:6.0.0]
	at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:770) ~[76:org.apache.wicket.core:6.0.0]
	at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:703) ~[76:org.apache.wicket.core:6.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:258) ~[76:org.apache.wicket.core:6.0.0]
	... 37 more
```

**Comment by jutzig** [comment]
I would assume there is quite a few issues with / in the branchname :-/
First step should be to add a validation to prevent this, then I need to have a look what would have to be done to actually support it.
